Write a function so that the columns of the output matrix are powers of the input
vector.

In [2]:
import numpy as np
a=[1,2,3,4,5]
print('Increasing Vandermonde matrix:\n',np.vander(a, increasing=True))
print('Decreasing Vandermonde matrix:\n',np.vander(a, increasing=False))

Increasing Vandermonde matrix:
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
Decreasing Vandermonde matrix:
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [3]:
b=[]
print('Original list:',a)
for i in a:
    temp=[]
    for j in range(len(a)):
        temp.append(i**j)
    b.append(temp)
print('Vander matrix:')
print(b)

Original list: [1, 2, 3, 4, 5]
Vander matrix:
[[1, 1, 1, 1, 1], [1, 2, 4, 8, 16], [1, 3, 9, 27, 81], [1, 4, 16, 64, 256], [1, 5, 25, 125, 625]]


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
inp=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
inp

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [10]:
from numpy import convolve
np.convolve(inp,np.ones(3),'valid')/3

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [21]:
N=len(inp)
k=3
for i in range(N-k+1):
    summ=0
    for j in range(i,i+k):
        summ+=inp[j]
    print('y'+str(i+1),':',summ/k)
    

y1 : 5.0
y2 : 4.666666666666667
y3 : 5.666666666666667
y4 : 6.666666666666667
y5 : 9.666666666666666
y6 : 28.666666666666668
y7 : 49.333333333333336
y8 : 72.66666666666667
y9 : 84.0
y10 : 93.33333333333333
y11 : 116.33333333333333
